%{?!ros_distro:%global ros_distro lyrical}
%global pkg_name hitch_estimation_apriltag_array
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-lyrical-hitch-estimation-apriltag-array
Version:        0.0.3
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
URL:            https://github.com/li9i/apriltag-hitch-estimation
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  python%{python3_pkgversion}-devel

%{?bloom_package}

%description
A package that estimates the hitch joint state between a robot and a trailer by
optical recognition of an array of April tags mounted at the front of the
trailer by the rear camera of the robot


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
A package that estimates the hitch joint state between a robot and a trailer by
optical recognition of an array of April tags mounted at the front of the
trailer by the rear camera of the robot


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
A package that estimates the hitch joint state between a robot and a trailer by
optical recognition of an array of April tags mounted at the front of the
trailer by the rear camera of the robot


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%py3_build


%install
%py3_install -- --prefix "%{bloom_prefix}"


%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "^\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Sun Jun 07 2026 li9i <alexandros.filotheou@gmail.com> - 0.0.3-1
- Autogenerated by Bloom
